version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: cd packages/yaml-script && npm install
            - run: cd packages/yaml-script && npm test
            - run: cd packages/yaml-script && npm pack

            - run: cd packages/d3-chart && npm install
            - run: cd packages/d3-chart && npm test
            - run: cd packages/d3-chart && npm pack

            - run: cd packages/model-editor && npm install
            - run: cd packages/model-editor && npm run test:unit

workflows:
    build-and-test:
      jobs:
        - build